services:
    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: example
            MARIADB_DATABASE: testlaravel
        volumes:
            - testlaraveldata:/var/lib/mysql
        ports:
            - 33061:3306
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 10251:1025
            - 8125:8025
volumes:
    testlaraveldata:
